export const SUBJECT_TYPES = {
  GS: "GS",
  OPTIONAL: "OPTIONAL",
};

export const TOPIC_STATUS = {
  NOT_STARTED: "NOT_STARTED",
  IN_PROGRESS: "IN_PROGRESS",
  REVISED: "REVISED",
  COMPLETED: "COMPLETED",
};

export const SUBTOPIC_STATUS = {
  NOT_STARTED: "NOT_STARTED",
  IN_PROGRESS: "IN_PROGRESS",
  REVISED: "REVISED",
  COMPLETED: "COMPLETED",
};